version: '3.8'

networks:
  nestjs-network:
services:
  api:
    container_name: nestjs_api_dev
    image: nestjs-api-dev:1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - nestjs-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:debug
    restart: unless-stopped
